-- MySQL Script generated by MySQL Workbench
-- Thu Nov  2 13:31:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema agencija
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agencija
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agencija` DEFAULT CHARACTER SET utf8 ;
USE `agencija` ;

-- -----------------------------------------------------
-- Table `agencija`.`Klijent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencija`.`Klijent` (
  `id` INT NOT NULL,
  `ime` VARCHAR(45) NULL,
  `prezime` VARCHAR(45) NULL,
  `broj_telefona` VARCHAR(45) NULL,
  `jmbg` VARCHAR(13) NULL,
  `broj_racuna` VARCHAR(45) NULL,
  `korisnicko_ime` VARCHAR(45) NULL,
  `lozinka` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencija`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencija`.`Admin` (
  `id` INT NOT NULL,
  `ime` VARCHAR(45) NULL,
  `prezime` VARCHAR(45) NULL,
  `korisnicko_ime` VARCHAR(45) NULL,
  `lozinka` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `admin` (`id`, `ime`, `prezime`, `korisnicko_ime`, `lozinka`) VALUES
(1, 'Marko', 'Marković', 'marko_markovic', 'marko123');

-- -----------------------------------------------------
-- Table `agencija`.`Bankovni_racun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencija`.`Bankovni_racun` (
  `id` INT NOT NULL,
  `broj_racuna` VARCHAR(45) NULL,
  `jmbg` VARCHAR(13) NULL,
  `stanje` DECIMAL(8,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `bankovni_racun` (`id`, `broj_racuna`, `jmbg`, `stanje`) VALUES
(1, '1111222233334444', '0101994000001', 10543.00),
(2, '1111222233335555', '0201994000011', 20022.00),
(3, '1111222233336666', '1105994000201', 5320.00),
(4, '1111222233337777', '2105998000001', 7892.00),
(5, '7777222233334444', '1508997110001', 11230.00),
(6, '7777222233331111', '2501999111000', 15420.00),
(7, '1234000056742918', '1104001118093', 14251.00),
(8, '7777222233339999', '0302999110201', 10002.00),
(9, '1111543233331234', '1907000113051', 7232.00),
(10, '1234567811112222', '2111993114021', 30259.00),
(11, '1234567887654321', '1102541293', 0.00);


-- -----------------------------------------------------
-- Table `agencija`.`Smjestaj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencija`.`Smjestaj` (
  `id` INT NOT NULL,
  `naziv` VARCHAR(45) NULL,
  `broj_zvjezdica` VARCHAR(45) NULL,
  `vrsta_sobe` VARCHAR(45) NULL,
  `cjena_po_nocenju` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencija`.`Aranzman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencija`.`Aranzman` (
  `id` VARCHAR(45) NOT NULL,
  `naziv_putovanja` VARCHAR(45) NULL,
  `destinacija` VARCHAR(45) NULL,
  `prevoz` VARCHAR(45) NULL,
  `datum_polaska` DATE NULL,
  `datum_dolaska` DATE NULL,
  `cijena_aranzmana` VARCHAR(45) NULL,
  `Smjestaj_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Destinacija_has_Smjestaj_Smjestaj1_idx` (`Smjestaj_id` ASC),
  CONSTRAINT `fk_Destinacija_has_Smjestaj_Smjestaj1`
    FOREIGN KEY (`Smjestaj_id`)
    REFERENCES `agencija`.`Smjestaj` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencija`.`Rezervacija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencija`.`Rezervacija` (
  `Klijent_id` INT NOT NULL,
  `Aranzman_id` VARCHAR(45) NOT NULL,
  `ukupna_cijena` VARCHAR(45) NULL,
  `placena_cijena` VARCHAR(45) NULL,
  PRIMARY KEY (`Klijent_id`, `Aranzman_id`),
  INDEX `fk_Klijent_has_Aranzman_Aranzman1_idx` (`Aranzman_id` ASC),
  INDEX `fk_Klijent_has_Aranzman_Klijent1_idx` (`Klijent_id` ASC),
  CONSTRAINT `fk_Klijent_has_Aranzman_Klijent1`
    FOREIGN KEY (`Klijent_id`)
    REFERENCES `agencija`.`Klijent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Klijent_has_Aranzman_Aranzman1`
    FOREIGN KEY (`Aranzman_id`)
    REFERENCES `agencija`.`Aranzman` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
